### ISSUE TITLE
OpenCV make instruction order

### ISSUE THREAD

**Issue by Pugnacioius** [ingxfm/license-plate-detection-raspberry-pi-3B-plus-OpenAlpr#2]
I don't think the instructions are in the correct order as presented:
cd /usr/src
sudo wget https://github.com/opencv/opencv/archive/4.2.0.zip
sudo mv 4.2.0.zip OpenCV-4.2.0.zip
sudo unzip -q OpenCV-4.2.0.zip
cd opencv-4.2.0
sudo mkdir release
cd cmake
cd release
sudo cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D ENABLE_PRECOMPILED_HEADERS=OFF ..
sudo make -j2
sudo make install

The release directory is created in the opencv-4.2.0 directory
Then you cannot cd to cmake
I think you need to cd to cmake first then execute the mkdir release, but if you cd to cmake how can you sudo cmake ?

**Comment by ingxfm** [comment]
Thank you. I have removed the "cd cmake". Now, I cd to release and then execute the sudo cmake...

**Comment by ingxfm** [comment]
Closing.
